image: localhost/local/oebuild

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  SSTATE_DIR: /cache/sstate
  DL_DIR: /cache/downloads
  TMPDIR: /cache/xilinx-minimal/$CI_COMMIT_BRANCH/tmp

build-job:
  stage: build
  script:
    - ls -l
    - pwd
    - rm -rf build
    - TEMPLATECONF=`pwd`/meta-xilinx-minimal/conf/templates/default  source ./openembedded-core/oe-init-build-env ./build ./bitbake
    - echo "DL_DIR = \"$DL_DIR\"" > conf/auto.conf
    - echo "SSTATE_DIR = \"$SSTATE_DIR\"" >> conf/auto.conf
    - echo "TMPDIR = \"$TMPDIR\"" >> conf/auto.conf
    - cat conf/auto.conf
    - id
    - bitbake core-image-minimal

test-job1:
  stage: test
  before_script:
    - source /home/oebuilds/labgrid-venv/bin/activate
    - labgrid-client -x 192.168.11.221 -p zcu104 acquire

  script:
    - source /home/oebuilds/labgrid-venv/bin/activate
    - cd meta-xilinx-minimal/contrib/labgrid
    - ls
    - pwd
    - mkdir images
    - cp $TMPDIR/deploy/images/zynqmp-zcu104-sdt-full/core-image-minimal-zynqmp-zcu104-sdt-full.rootfs.wic.qemu-sd images/image.wic.qemu-sd
    - pytest --lg-coordinator=192.168.11.221 --lg-env zcu104.yaml test_uboot_strategy.py

  after_script:
    - source /home/oebuilds/labgrid-venv/bin/activate
    - labgrid-client -x 192.168.11.221 -p zcu104 power off
    - labgrid-client -x 192.168.11.221 -p zcu104 release

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
